---
- name: Configure kubernetes master
  hosts: master_nodes
  become: true
  roles:
    - kubernetes_master

- name: Configure kubernetes network
  hosts: master_nodes
  become: true
  roles:
    - kubernetes_network

- name: Configure kubernetes worker nodes
  hosts: worker_nodes
  become: true
  roles:
    - kubernetes_worker

- name: Install and configure MetalLB load balancer
  hosts: master_nodes
  become: true
  roles:
    - metallb

- name: Configure Local Storage
  hosts: master_nodes
  become: true
  roles:
    - storage

- name: Configure Monitoring
  hosts: master_nodes
  become: true
  roles:
    - monitoring

- name: Deploy demo application to test MetalLB
  hosts: master_nodes
  become: true
  roles:
    - demo_app
